name: Build Windows App

on: workflow_dispatch # 触发构建的事件，这里是每次推送时
  

jobs:
  build:
    runs-on: windows-2019 # 运行环境
    defaults:
      run:
        shell: powershell
    steps:
    - uses: actions/checkout@v2 # 检出代码
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # 设置Node.js版本, winax支持的Node.js版本，根据需要调整
        architecture: 'x86'
    - name: Install Python and Build Tools
      run: |
        npm install --global --production windows-build-tools --vs2017
      env:
        npm_config_arch: "ia32"
        
    - name: Check Node.js and npm version
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm install # 安装依赖
    - name: Build Electron app
      run: npm run release # 构建应用，确保你有相应的脚本在package.json中
    - name: Package Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub令牌，用于在构建过程中下载依赖项
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # 打包应用为Windows可执行程序
        args: --windows portable
    - name: Upload to MinIO
      env:
        MINIO_ENDPOINT: your_minio_endpoint # 例如: play.min.io
        MINIO_BUCKET: your_bucket_name
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      run: |
        docker run --entrypoint=/bin/sh minio/mc -c "
        mc alias set minio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        mc cp dist/*.exe minio/$MINIO_BUCKET/"
